name: Create Tag and Release

on:
  pull_request:
    types:
      - closed

jobs:
  create:
    if: startsWith(github.head_ref, 'release/') != true && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Check for version changes in openapi.yaml and extract version
        id: extract_version
        run: |
          # Check out the merged commit directly using GITHUB_SHA
          git checkout ${{ github.sha }}

          # Check if the version line in openapi.yaml has changed between the base and the current commit
          if git diff origin/${{ github.event.pull_request.base.ref }} $GITHUB_SHA -- openapi.yaml | grep -E '^\+  version:|^-  version:'; then
            # Extract the new version number from openapi.yaml
            version=$(grep '^  version:' openapi.yaml | sed 's/version: //')
            echo "custom_tag=$version" >> $GITHUB_OUTPUT
          else
            echo "openapi.yaml のバージョン部分に変更がありません。アクションを終了します。"
            exit 0
          fi
        shell: bash

      - name: Create a tag
        id: tag_version
        if: steps.extract_version.outputs.custom_tag != ''
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.extract_version.outputs.custom_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
