name: Create Tag if Not Exists

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag_if_not_exists:
    if: startsWith(github.head_ref, 'release/') != true && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from openapi.yaml
        id: extract_version
        run: |
          # Extract the version number from openapi.yaml
          version=$(grep '^  version:' openapi.yaml | sed 's/version: //')
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create a tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.extract_version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix:
