name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: git config --global --add safe.directory /github/workspace

      - name: Check if the tag matches the pattern
        id: tag_check
        run: |
          echo $GITHUB_REF
          if [[ "$GITHUB_REF" =~ refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag matches the pattern"
          else
            echo "Tag does not match the pattern"
            exit 1
          fi

      - name: Install GitHub CLI
        if: steps.tag_check.outcome == 'success'
        run: sudo apt-get install -y gh

      - name: Generate and create release
        if: steps.tag_check.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create $RELEASE_VERSION --generate-notes --title "Release $RELEASE_VERSION" --notes ""
