name: Create Release

on:
  push:
    tags:
      - "*.*.*" # タグが `X.Y.Z` の形式にマッチする場合にトリガー
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: git config --global --add safe.directory /github/workspace

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Generate and create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          RELEASE_NOTES=$(gh release create $RELEASE_VERSION --generate-notes --title "Release $RELEASE_VERSION" --notes "")
          echo "$RELEASE_NOTES"
