name: Create Release on Tag Push to Main

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: |
          git fetch --tags --force

      - name: Set up Git
        run: git config --global --add safe.directory /github/workspace

      - name: Get latest tag
        id: get_tag
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view ${{ env.LATEST_TAG }} >/dev/null 2>&1; then
            echo "${{ env.LATEST_TAG }} の Release はすでに存在しているため Release の作成をスキップします"
            echo "::set-output name=release_exists::true"
          else
            echo "${{ env.LATEST_TAG }} の Release はまだ存在しないため Release を作成します"
            echo "::set-output name=release_exists::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        if: steps.check_release.outputs.release_exists == 'false'
        run: sudo apt-get install -y gh

      - name: Create release
        if: steps.check_release.outputs.release_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_TAG: ${{ env.LATEST_TAG }}
        run: |
          gh release create $LATEST_TAG --generate-notes --title "Release $LATEST_TAG" --notes ""
